name = "qzk"
compatibility_date = "2025-01-01"
pages_build_output_dir = "./.svelte-kit/cloudflare"

[placement]
mode = "smart"

[[d1_databases]]
binding = "DB"
database_name = "your-database-name"
database_id = "...your id here..."
